// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBscuWdMO8vmON06pQ2WMnDnQgadiUIIXs',
    appId: '1:443824671113:web:8d800c6bcdb5707969b958',
    messagingSenderId: '443824671113',
    projectId: 'ecomm-f9744',
    authDomain: 'ecomm-f9744.firebaseapp.com',
    storageBucket: 'ecomm-f9744.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm2x-W2QV5rjWLdUzzRlK9q82zGGLzCMg',
    appId: '1:443824671113:android:bfcbb7c32fff7b0a69b958',
    messagingSenderId: '443824671113',
    projectId: 'ecomm-f9744',
    storageBucket: 'ecomm-f9744.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAliNqaUmWdMJllN8tCAUwsa__IxoW-Xi8',
    appId: '1:443824671113:ios:7382a57d7c9d005569b958',
    messagingSenderId: '443824671113',
    projectId: 'ecomm-f9744',
    storageBucket: 'ecomm-f9744.appspot.com',
    androidClientId: '443824671113-4f52mm3khum0jnkmu9ecpa2mklunf58r.apps.googleusercontent.com',
    iosClientId: '443824671113-1eq0bpodlu0r5an6cnl3p1ps82af84u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboardEcommerces',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAliNqaUmWdMJllN8tCAUwsa__IxoW-Xi8',
    appId: '1:443824671113:ios:7382a57d7c9d005569b958',
    messagingSenderId: '443824671113',
    projectId: 'ecomm-f9744',
    storageBucket: 'ecomm-f9744.appspot.com',
    androidClientId: '443824671113-4f52mm3khum0jnkmu9ecpa2mklunf58r.apps.googleusercontent.com',
    iosClientId: '443824671113-1eq0bpodlu0r5an6cnl3p1ps82af84u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboardEcommerces',
  );
}
